---
language: ruby

script: "source api_tokens_for_travis.sh && ruby test.rb"

os:
  - linux
  - osx
rvm:
  - ruby-head
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
  - jruby-head
matrix:
  allow_failures:
  # NetHTTPUtils does not pass query params or smth
  - rvm: jruby-head
    os: osx
  # the "Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m" output at jruby start ruins binstub tests
  # TODO: -W0 does not help but probably there is another option or I should patch tests for jruby
  - rvm: jruby-head
    os: linux
