---
language: ruby

script: "source api_tokens_for_travis.sh && ruby test.rb"

os:
  - linux
  - osx
rvm:
  - ruby-head
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
  - jruby-head
matrix:
  allow_failures:   # seems like NetHTTPUtils does not pass query params or smth
  - rvm: jruby-head
    os: osx
